# Generated by Django 4.2.27 on 2025-12-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='events',
            field=models.JSONField(default=list),
        ),
    ]
